
orqnibkshlapwhjjmszh = "2024-05-22T19:29:00Z"

[functions.db-utils]
verify_jwt = true

[functions.create-sql-function]
verify_jwt = true

[functions.update-product-segments-function]
verify_jwt = true
