// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orqnibkshlapwhjjmszh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ycW5pYmtzaGxhcHdoamptc3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMjQxNDAsImV4cCI6MjA2MTgwMDE0MH0.JkNLF_MgpA4KamUZspxidu6wT4bCXEw8ej93xbp0JsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);